 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 workflows:
   primary:
     jobs:
       - build:
          context: Common
       - deploy:
          context: Common
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
 jobs:
   build:
     executor: win/default         
     steps:
       - checkout
       - run: msbuild PlaybackIcons/PlaybackIcons.vcxproj /p:Configuration=Release
       - run: msbuild amp/amp.csproj /t:restore
       - run: msbuild amp/amp.csproj /p:Configuration=Release
       - run: pip install mkdocs
       - run: pip install mkdocs-ezlinks-plugin
   deploy:
     executor: win/default     
     steps:
     - checkout
     - run: msbuild PlaybackIcons/PlaybackIcons.vcxproj /p:Configuration=Release
     - run: msbuild amp/amp.csproj /t:restore
     - run: msbuild amp/amp.csproj /p:Configuration=Release     
     - run: choco install wixtoolset
     - run: msbuild InstallerBaseWixSharp/InstallerBaseWixSharp.csproj /t:restore
     - run: msbuild InstallerBaseWixSharp/InstallerBaseWixSharp.csproj /p:Configuration=Release       
     - run: 
        name: Release a tag
        command: |
          choco install gitreleasemanager.portable            
          InstallerBaseWixSharp/github_release.ps1
