 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 workflows:
   primary:
     jobs:
       - build:
          context: Common
       - deploy:
          requires:
            - build       
          context: Common
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: choco install wixtoolset
       - run: msbuild amp/amp.csproj /t:restore
       - run: msbuild amp/amp.csproj /p:Configuration=Release
       - run: msbuild InstallerBaseWixSharp/InstallerBaseWixSharp.csproj /t:restore
       - run: msbuild InstallerBaseWixSharp/InstallerBaseWixSharp.csproj /p:Configuration=Release       
   deploy:
     executor: win/default     
     steps:
       - run: 
          name: Release a tag
          command: |
            choco install gitreleasemanager.portable            
            InstallerBaseWixSharp/github_release.ps1
