 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 workflows:
   primary:
     jobs:
       - build:
          context: Common

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: msbuild amp/amp/amp.csproj /t:restore
       - run: msbuild amp/amp/amp.csproj /p:Configuration=Release
       - run: msbuild amp/InstallerBaseWixSharp/InstallerBaseWixSharp.csproj /t:restore
       - run: msbuild amp/InstallerBaseWixSharp/InstallerBaseWixSharp.csproj /p:Configuration=Release       