 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 workflows:
   primary:
     jobs:
       - build:
          context: Common

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: choco install wixtoolset
       - run: msbuild amp/amp.csproj /t:restore
       - run: msbuild amp/amp.csproj /p:Configuration=Release
       - run: msbuild InstallerBaseWixSharp/InstallerBaseWixSharp.csproj /t:restore
       - run: msbuild InstallerBaseWixSharp/InstallerBaseWixSharp.csproj /p:Configuration=Release       
       - run: 
          name: Release a tag
          command: |
            amp/github_release.ps1
