name: .NET Desktop

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'amp.Database/**'
      - 'amp.EtoForms/**'
      - 'amp.Playback/**'
      - 'amp.Shared/**'
      - 'amp.Tests/**'
      - 'EtoForms.Controls.Custom/**'    
    
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'amp.Database/**'
      - 'amp.EtoForms/**'
      - 'amp.Playback/**'
      - 'amp.Shared/**'
      - 'amp.Tests/**'
      - 'EtoForms.Controls.Custom/**'    

jobs:

  build:
    environment: WinformsAppBuild
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022  # For a list of available runner types, refer to
                           # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: amp.sln
      App_Project_Directory: amp
      App_Project_Path: amp\amp.csproj
      Icon_Dll_Project_Path: PlaybackIcons\PlaybackIcons.vcxproj      
      BUILD_CONFIGURATION: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET 6 workload
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:App_Project_Path /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the Icon DLL project for the amp#
    - name: Build the Icon DLL project for the amp#
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.Icon_Dll_Project_Path}}

    # Build the amp# project
    - name: Build the amp# project
      run: msbuild $env:App_Project_Path /p:Configuration=$env:Configuration
