name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Build
      run: dotnet build --no-restore
      working-directory: "$GITHUB_WORKSPACE/amp.EtoForms"
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: "$GITHUB_WORKSPACE/amp.Tests"
